### ISSUE TITLE
mainactivity.java question

### ISSUE THREAD

**Issue by kalvin1981** [dimalinux/SwipeYours#1]
30     private static final DateFormat timeStampFmt = new SimpleDateFormat("HH:mm:ss.SSS  ", Locale.US); 

does this mean that only US cards will work, or that it will only work in the US
I live in Canada will my Canadian card work with your app in Canada?

**Comment by dimalinux** [comment]
No, that's just the logging for people interested in how the protocol works and what bits are being sent back and forth across the NFC interface.  It will probably work in Canada.  The North America restriction is because POS systems outside the United States are unlikely to support the older and less secure Visa Magstripe protocol.
