### ISSUE TITLE
AIP value.

### ISSUE THREAD

**Issue by 0x016F2818** [dimalinux/SwipeYours#2]
I'm not sure about it.
The AIP (tag 82 which is part of GPO R-APDU) consists of 2 bytes, of which the second byte is RFU, while the first byte encodes the stages of the EMV debit/credit transaction flow and the corresponding application functions that are actually supported by the card.
I noticed the you implemented it in reverse. am I wrong ?
`private static final byte[] GPO_COMMAND_RESPONSE = {`
`(byte) 0x80,`
`(byte) 0x06,`
`(byte) 0x00,`
`(byte) 0x80, /* this should be RFU */`
`(byte) 0x08,`
`(byte) 0x01,`
`(byte) 0x01,`
`(byte) 0x00,`
`(byte) 0x90,  // SW1`
`(byte) 0x00   // SW2`
`};`

**Comment by dimalinux** [comment]
I'd like to document the GPO_COMMAND_RESPONSE better if anyone can help.  I believe having the first bit of the second byte of the AIP set to 1 is what tells the reader to use Visa MSD (verses qVSDC).  The Visa MSD protocol might not be EMV compliant in this regard.  Maybe it should be "reserved for past use" instead of future.  :)
